name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Key Passphrase
        run: echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add -

      - name: Deploy to Server
        run: |
          ssh proof@ssh-proof.alwaysdata.net "cd /home/proof/www/ && git pull origin main && sudo reboot"
