name: Deployment Workflow

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ssh-proof.alwaysdata.net
          username: proof
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/proof/www/
            git pull origin main
            sudo reboot
